services:
  khsd-api-peoplesoft:
    build: .
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=mssql+pyodbc://username:password@your-sql-server/your-db?driver=ODBC+Driver+17+for+SQL+Server
      - API_KEY=your_api_key
    restart: unless-stopped
